### ISSUE TITLE
Last updated sollte vom Backend gesetzt werden

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/gatemon-html#4]
Momentan hat angeblich einer der Nodes zuletzt am 16.01.2016 geupdated - also 8 Tage in der Zukunft.

Um solch unsinnige Angaben zu vermeiden sollte das Backend das Feld `lastupdated` setzen und die Daten des Nodes bei zu starker Abweichung vom aktuellen Zeitpunkt am besten gleich ganz verwerfen.

**Comment by ghost** [comment]
Pull request pls?
